name: Mon premier pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building the project..."

  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Running tests..."

  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying the project..."

